/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Cibic {
  Cibic._();

  static const _kFontFam = 'Cibic';
  static const _kFontPkg = null;

  static const IconData abstain = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData citizen_points = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_post = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData public = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData results = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
