/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData user = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData results = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData public = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe808, fontFamily: _kFontFam);
}
